export const data =[
    {
        id:1,
       thumbnail:"https://i.ibb.co/ZNz7x27/0424935d-c422-441d-8644-a74f724916cb.jpg",
       thumbnailcae:"https://i.ibb.co/N90cmm2/CAE-certificate-for-sale.jpg",
       thumbnailfce:"https://i.ibb.co/pQQkCtW/OIP-5.jpg",
       thumbnailcpe:" ",
       dateAdded:"05/01/2023",
       title:"Writing Templates",
       type:"Writing",
       enlace: "https://docs.google.com/document/d/1ynAsrV2Uj-uR0qrCDzGvDw8I2sXYlzEg/edit?usp=sharing&ouid=114172849724389982127&rtpof=true&sd=true",
       description:"Modelo para cada tipo de writings con expresions pre establecidas que deberias incluirpara asgura la mayor cantidad de puntos.",
    },
    {
        id:2,
       thumbnail:"https://i.ibb.co/qkbmhzc/2991c730-a8c5-4711-8390-9c8919778d3e.jpg",
       thumbnailcae:"https://i.ibb.co/N90cmm2/CAE-certificate-for-sale.jpg",
       thumbnailfce:"https://i.ibb.co/pQQkCtW/OIP-5.jpg",
       thumbnailcpe:"https://i.ibb.co/TPGSMC5/cpe-1.png ",
       dateAdded:"05/01/2023",

       title:"Speaking Part 1",
       type:"Speaking",
       enlace: "https://docs.google.com/document/d/18XLLq6gRiQqTNU4iIiI0qzc6epBd8hBQ/edit?usp=sharing&ouid=114172849724389982127&rtpof=true&sd=true",
       description:"Frases para obtener el mayor puntaje en la parte 1 donde las preguntas son de informacion personal y se puede obtener mejor nota",
    },
    {
        id:3,
       thumbnail:"https://i.ibb.co/pnV9pg7/46bb013c-ecde-4c81-85f5-57aa640afcaf.jpg",
       thumbnailcae:"https://i.ibb.co/N90cmm2/CAE-certificate-for-sale.jpg",
       thumbnailfce:"https://i.ibb.co/pQQkCtW/OIP-5.jpg",
       thumbnailcpe:"https://i.ibb.co/TPGSMC5/cpe-1.png ",
       dateAdded:"05/01/2023",

       title:"Speaking Part 2",
       type:"Speaking",
       enlace: "https://docs.google.com/document/d/1cn5Fz9vBTkNgrrOrb0lpflG0VC35__NP/edit?usp=sharing&ouid=114172849724389982127&rtpof=true&sd=true",
       description:"Frases para obtener el mayor puntaje en la parte 1 donde las preguntas son de informacion personal y se puede obtener mejor nota",
    },
    {
        id:4,
       thumbnail:"https://i.ibb.co/j8LRRJZ/6be03a7d-7ba3-402e-9eb3-d5d1f75d78c3.jpg",
       thumbnailcae:"https://i.ibb.co/N90cmm2/CAE-certificate-for-sale.jpg",
       thumbnailfce:"https://i.ibb.co/pQQkCtW/OIP-5.jpg",
       thumbnailcpe:"https://i.ibb.co/TPGSMC5/cpe-1.png ",
       dateAdded:"05/01/2023",

       title:"Speaking Part 3 - 4",
       type:"Speaking",
       enlace: "https://docs.google.com/document/d/1uNFaRWS_kuBKwQtr5L6vf3vTwcejt-B7/edit?usp=sharing&ouid=114172849724389982127&rtpof=true&sd=true",
       description:"Frases para obtener el mayor puntaje en la parte 1 donde las preguntas son de informacion personal y se puede obtener mejor nota",
    },
    {
        id:5,
       thumbnail:"https://i.ibb.co/0YfgNK6/18b7b46c-c92c-452e-a8fd-6031883513d4.jpg",
       thumbnailcae:" ",
       thumbnailfce:"https://i.ibb.co/pQQkCtW/OIP-5.jpg",
       thumbnailcpe:" ",
       dateAdded:"05/01/2023",

       title:"10 Preguntas de examen – Speaking Parte 1 (Entrevista) | B2 First (FCE) ",
       type:"Speaking",
       enlace: "https://docs.google.com/document/d/1kXkFOi-IFJP83_QTg6SZNKGfiSpI5IFXAlcTJmgwkJE/edit?usp=sharing",
       description:"Frases para obtener el mayor puntaje en la parte 1 donde las preguntas son de informacion personal y se puede obtener mejor nota",
    },
    {
        id:6,
       thumbnail:"https://i.ibb.co/JrLp8X2/ee20dcf4-7dd2-475b-980a-c7b6687a462f.jpg",
       thumbnailcae:" ",
       thumbnailfce:"https://i.ibb.co/pQQkCtW/OIP-5.jpg",
       thumbnailcpe:" ",
       dateAdded:"05/01/2023",

       title:"Prepositions After Verbs & Adjectives ",
       type:"Grammar",
       enlace: "https://docs.google.com/document/d/1CeVFrtcUUUYYfBOyHIvXkZ0mUjl3vx7ri-L0BYkARd8/edit?usp=sharing",
       description:"Frases para obtener el mayor puntaje en la parte 1 donde las preguntas son de informacion personal y se puede obtener mejor nota",
    }
]